const { SchemaType: GeminiSchemaType } = require("@google/generative-ai");

const studyContnetSchema = {
    description: "Schema for a personalized study content module generated by AI.",
    type: GeminiSchemaType.OBJECT,
    properties: {
        topic: {
            type: GeminiSchemaType.STRING,
            description: "Title of the topic being studied.",
            nullable: false,
        },
        subject: {
            type: GeminiSchemaType.STRING,
            description: "The subject to which this topic belongs.",
            nullable: false,
        },
        difficulty: {
            type: GeminiSchemaType.STRING,
            description: "Estimated difficulty level for the topic (easy, medium, hard).",
            nullable: false,
        },
        estimated_study_time: {
            type: GeminiSchemaType.STRING,
            description: "Approximate time needed to study the topic (e.g., '2 hours').",
            nullable: false,
        },
        readme: {
            type: GeminiSchemaType.STRING,
            description: "A comprehensive markdown-formatted README explanation of the topic.",
            nullable: false,
        },
        quiz: {
            type: GeminiSchemaType.ARRAY,
            description: "List of quiz questions to assess understanding of the topic.",
            items: {
                type: GeminiSchemaType.OBJECT,
                properties: {
                    question: {
                        type: GeminiSchemaType.STRING,
                        description: "The question being asked.",
                        nullable: false,
                    },
                    options: {
                        type: GeminiSchemaType.ARRAY,
                        description: "List of answer options for the question.",
                        items: {
                            type: GeminiSchemaType.STRING,
                            nullable: false,
                        },
                        nullable: false,
                    },
                    correct_answer: {
                        type: GeminiSchemaType.STRING,
                        description: "The correct answer from the options.",
                        nullable: false,
                    },
                    explanation: {
                        type: GeminiSchemaType.STRING,
                        description: "Detailed explanation of why the answer is correct.",
                        nullable: false,
                    },
                },
                required: ["question", "options", "correct_answer", "explanation"],
            },
            nullable: false,
        },
    },
    required: ["topic", "subject", "difficulty", "estimated_study_time", "readme", "quiz"],
};

module.exports = { studyContnetSchema };
